### ISSUE TITLE
Issue with Linear Learner Algorithm while transform

### ISSUE THREAD

**Issue by hdamani09** [aws/sagemaker-spark#101]
Please fill out the form below.

### System Information
- **Spark**:
- **SDK Version**:spark_2.2.0-1.2.5
- **Spark Version**:2.4.3
- **Algorithm**: LinearLearner

### Describe the problem
Hello,
I trained a model with linear learner algorithm using the following hyperparameters and sample csv dataset :

```
"feature_dim": "6",
"predictor_type": "binary_classifier",
"mini_batch_size": "15"
```
```
+-----+---+---+-----+---------------+----+----+
|label|sex|age| Time|Number_of_Warts|Type|Area|
+-----+---+---+-----+---------------+----+----+
| 0| 1| 17| 9.25| 12| 1| 10|
| 0| 1| 17| 11.5| 2| 1| 10|
| 0| 1| 23|10.25| 7| 3| 72|
| 0| 1| 29|11.75| 5| 1| 96|
| 0| 1| 34| 12.0| 1| 3| 150|
| 0| 1| 40| 11.5| 9| 2| 80|
| 0| 1| 50| 8.0| 1| 3| 132|
| 0| 1| 50| 8.75| 11| 3| 132|
| 0| 1| 63| 2.75| 3| 3| 20|
| 0| 1| 67| 9.25| 1| 1| 42|
| 0| 2| 23|11.75| 12| 3| 72|
| 0| 2| 24| 9.5| 3| 3| 20|
| 0| 2| 27| 8.75| 2| 1| 6|
| 0| 2| 32| 12.0| 4| 3| 750|
| 0| 2| 34|11.25| 3| 3| 150|
| 0| 2| 34| 12.0| 3| 3| 95|
| 0| 2| 35| 8.5| 6| 3| 100|
| 0| 2| 36| 10.5| 4| 1| 8|
| 0| 2| 36| 11.0| 6| 1| 8|
| 0| 2| 50| 9.5| 4| 3| 132|
+-----+---+---+-----+---------------+----+----+
only showing top 20 rows
```
The model was successfully trained for the above structured dataset, after it was fit. But when I'm trying to perform a **transform** for the feature vector assembled dataframe of the below structure, it seems it's able to get the predictions but throwing a **java.lang.NumberFormatException** as well.

```
+------------------------------+
|features |
+------------------------------+
|[1.0,17.0,9.25,12.0,1.0,10.0] |
|[1.0,17.0,11.5,2.0,1.0,10.0] |
|[1.0,23.0,10.25,7.0,3.0,72.0] |
|[1.0,29.0,11.75,5.0,1.0,96.0] |
|[1.0,34.0,12.0,1.0,3.0,150.0] |
|[1.0,40.0,11.5,9.0,2.0,80.0] |
|[1.0,50.0,8.0,1.0,3.0,132.0] |
|[1.0,50.0,8.75,11.0,3.0,132.0]|
|[1.0,63.0,2.75,3.0,3.0,20.0] |
|[1.0,67.0,9.25,1.0,1.0,42.0] |
|[2.0,23.0,11.75,12.0,3.0,72.0]|
|[2.0,24.0,9.5,3.0,3.0,20.0] |
|[2.0,27.0,8.75,2.0,1.0,6.0] |
|[2.0,32.0,12.0,4.0,3.0,750.0] |
|[2.0,34.0,11.25,3.0,3.0,150.0]|
|[2.0,34.0,12.0,3.0,3.0,95.0] |
|[2.0,35.0,8.5,6.0,3.0,100.0] |
|[2.0,36.0,10.5,4.0,1.0,8.0] |
|[2.0,36.0,11.0,6.0,1.0,8.0] |
|[2.0,50.0,9.5,4.0,3.0,132.0] |
+------------------------------+
only showing top 20 rows

root
|-- features: vector (nullable = true)
```

### Minimal repo / logs
```
org.apache.spark.SparkException : Job aborted due to stage failure: Task 0 in stage 14.0 failed 4 times, most recent failure: Lost task 0.3 in stage 14.0 (TID 16, ip-172-21-85-53.aws.com, executor 1): java.lang.NumberFormatException: For input string: "1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
1.0
0.0
0.0"
at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
at java.lang.Double.parseDouble(Double.java:538)
at scala.collection.immutable.StringLike$class.toDouble(StringLike.scala:285)
at scala.collection.immutable.StringOps.toDouble(StringOps.scala:29)
at com.amazonaws.services.sagemaker.sparksdk.transformation.deserializers.XGBoostCSVRowDeserializer$$anonfun$deserializeResponse$1.apply(XGBoostCSVRowDeserializer.scala:41)
at com.amazonaws.services.sagemaker.sparksdk.transformation.deserializers.XGBoostCSVRowDeserializer$$anonfun$deserializeResponse$1.apply(XGBoostCSVRowDeserializer.scala:41)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:186)
at com.amazonaws.services.sagemaker.sparksdk.transformation.deserializers.XGBoostCSVRowDeserializer.deserializeResponse(XGBoostCSVRowDeserializer.scala:41)
at com.amazonaws.services.sagemaker.sparksdk.transformation.util.RequestBatchIterator.hasNext(RequestBatchIterator.scala:136)
at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
at org.apache.spark.sql.execution.columnar.CachedRDDBuilder$$anonfun$1$$anon$1.hasNext(InMemoryRelation.scala:125)
at org.apache.spark.storage.memory.MemoryStore.putIterator(MemoryStore.scala:221)
at org.apache.spark.storage.memory.MemoryStore.putIteratorAsValues(MemoryStore.scala:299)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1165)
at org.apache.spark.storage.BlockManager$$anonfun$doPutIterator$1.apply(BlockManager.scala:1156)
at org.apache.spark.storage.BlockManager.doPut(BlockManager.scala:1091)
at org.apache.spark.storage.BlockManager.doPutIterator(BlockManager.scala:1156)
at org.apache.spark.storage.BlockManager.getOrElseUpdate(BlockManager.scala:882)
at org.apache.spark.rdd.RDD.getOrCompute(RDD.scala:335)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:286)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
at org.apache.spark.scheduler.Task.run(Task.scala:121)
at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:408)
at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:414)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
```

Is this a bug with the linear learner algorithm because the same dataset worked fine with XGBoost algorithm while doing a transform on the feature Vector Assembled dataframe on the trained model?

**Comment by laurenyu** [comment]
Thanks for using SageMaker! I've reached out to the team that owns Linear Learner to see if they have any insight.

**Comment by yuanzhua** [comment]
Thank you for reaching out. The call stack indicates you have something wrong with XGBoost, but in your recent message you have called out it might be a bug with the linear learner. Could you help confirm whether you have shared the correct call stack or you did mean a bug in XGBoost? Much appreciated.
