### ISSUE TITLE
XGBoostSageMakerEstimator() can not handle a dataframe with extra columns other than "features" and "label"

### ISSUE THREAD

**Issue by mostafa-time** [aws/sagemaker-spark#12]
When calling XGBoostSageMakerEstimator(), the input dataframe can not have more columns other than "features" and "label". This is inconsistent with SparkML pipelines where one can have multiple transformations and each transformation just picks the relevant columns.

This works:

```python
xgb_estimator = XGBoostSageMakerEstimator(
    trainingInstanceType="ml.m4.xlarge",
    trainingInstanceCount=1,
    endpointInstanceType="ml.m4.xlarge",
    endpointInitialInstanceCount=1,
    sagemakerRole=IAMRole(iam_role))
xgb_estimator.setNumRound(2)
xgb_model = xgb_estimator.fit(algoInput.select("features","label")) 
```
This does not:
```python
xgb_estimator = XGBoostSageMakerEstimator(
    trainingInstanceType="ml.m4.xlarge",
    trainingInstanceCount=1,
    endpointInstanceType="ml.m4.xlarge",
    endpointInitialInstanceCount=1,
    sagemakerRole=IAMRole(iam_role))
xgb_estimator.setNumRound(2)
xgb_model = xgb_estimator.fit(algoInput.select("features","label","C17848"))
```

Stack trace:
```py4j.protocol.Py4JJavaError: An error occurred while calling o347.fit.
: java.io.IOException: Illegal schema for libsvm data, schema=StructType(StructField(features,org.apache.spark.ml.linalg.VectorUDT@3bfc3ba7,true), StructField(label,DoubleType,true), StructField(C17848,StringType,true))
        at org.apache.spark.ml.source.libsvm.LibSVMFileFormat.verifySchema(LibSVMRelation.scala:82)
        at org.apache.spark.ml.source.libsvm.LibSVMFileFormat.prepareWrite(LibSVMRelation.scala:122)
        at org.apache.spark.sql.execution.datasources.FileFormatWriter$.write(FileFormatWriter.scala:135)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:145)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.datasources.DataSource.writeInFileFormat(DataSource.scala:435)
        at org.apache.spark.sql.execution.datasources.DataSource.write(DataSource.scala:471)
        at org.apache.spark.sql.execution.datasources.SaveIntoDataSourceCommand.run(SaveIntoDataSourceCommand.scala:50)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:58)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:56)
        at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExecute(commands.scala:74)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$1.apply(SparkPlan.scala:117)
        at org.apache.spark.sql.execution.SparkPlan$$anonfun$executeQuery$1.apply(SparkPlan.scala:138)
        at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
        at org.apache.spark.sql.execution.SparkPlan.executeQuery(SparkPlan.scala:135)
        at org.apache.spark.sql.execution.SparkPlan.execute(SparkPlan.scala:116)
        at org.apache.spark.sql.execution.QueryExecution.toRdd$lzycompute(QueryExecution.scala:92)
        at org.apache.spark.sql.execution.QueryExecution.toRdd(QueryExecution.scala:92)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:609)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:233)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:217)
        at com.amazonaws.services.sagemaker.sparksdk.internal.DataUploader.writeData(DataUploader.scala:111)
        at com.amazonaws.services.sagemaker.sparksdk.internal.DataUploader.uploadData(DataUploader.scala:90)
        at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.fit(SageMakerEstimator.scala:299)
        at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.fit(SageMakerEstimator.scala:175)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)```

**Comment by andremoeller** [comment]
Hi @mostafa-time,

Thanks for using SageMaker Spark!

`XGBoostSageMakerEstimator` delegates writing training data to LibSVM-formatted files to S3 to Spark's LibSVMOutputWriter, which is fairly restrictive in it's schema validation:

https://github.com/apache/spark/blob/930b90a84871e2504b57ed50efa7b8bb52d3ba44/mllib/src/main/scala/org/apache/spark/ml/source/libsvm/LibSVMRelation.scala#L79

You can use the `trainingProjectedColumns` parameter to select only the "label" and "features" columns, so you can still put the `XGBoostSageMakerEstimator` in a Spark `Pipeline`:

https://github.com/aws/sagemaker-spark/blob/c33ee6ed84f9fc86780c8e35e2b0d36b60437bd1/sagemaker-spark-sdk/src/main/scala/com/amazonaws/services/sagemaker/sparksdk/algorithms/XGBoostSageMakerEstimator.scala#L430-L432

Does this answer your question? If not, feel free to let us know. Thanks!

**Comment by mostafa-time** [comment]
Hi @andremoeller!

When I modify the code:
```python
xgb_estimator = XGBoostSageMakerEstimator(
    trainingInstanceType="ml.m4.xlarge",
    trainingInstanceCount=1,
    endpointInstanceType="ml.m4.xlarge",
    endpointInitialInstanceCount=1,
    trainingProjectedColumns = ["features","label"],
    sagemakerRole=IAMRole(iam_role))

xgb_estimator.setNumRound(2)
xgb_model = xgb_estimator.fit(algoInput.select)
```
This is what I get:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sagemaker_pyspark/SageMakerEstimator.py", line 253, in fit
    return self._call_java("fit", dataset)
  File "/usr/local/lib/python2.7/site-packages/sagemaker_pyspark/wrapper.py", line 76, in _call_java
    java_value = super(SageMakerJavaWrapper, self)._call_java(name, *java_args)
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 50, in _call_java
    java_args = [_py2java(sc, arg) for arg in args]
  File "/usr/lib/spark/python/pyspark/ml/common.py", line 85, in _py2java
    data = bytearray(PickleSerializer().dumps(obj))
  File "/usr/lib/spark/python/pyspark/serializers.py", line 451, in dumps
    return pickle.dumps(obj, protocol)
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```

**Comment by andremoeller** [comment]
Hey @mostafa-time ,

At first glance, the problem might be that `algoInput.select` instead of `algoInput` is used as the input to `fit()`:

```
xgb_model = xgb_estimator.fit(algoInput.select)
 ```

Could you try `xgb_estimator.fit(algoInput)` instead?

Thanks!

**Comment by mostafa-time** [comment]
Oh @andremoeller , that was such a rookie mistake! Sorry about that.... however this is the stack trace with removing .select:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/sagemaker_pyspark/SageMakerEstimator.py", line 253, in fit
    return self._call_java("fit", dataset)
  File "/usr/local/lib/python2.7/site-packages/sagemaker_pyspark/wrapper.py", line 76, in _call_java
    java_value = super(SageMakerJavaWrapper, self)._call_java(name, *java_args)
  File "/usr/lib/spark/python/pyspark/ml/wrapper.py", line 51, in _call_java
    return _java2py(sc, m(*java_args))
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
  File "/usr/lib/spark/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/usr/lib/spark/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o217.fit.
: java.lang.ClassCastException: java.util.ArrayList cannot be cast to scala.collection.immutable.List
        at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.fit(SageMakerEstimator.scala:297)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:280)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:214)
        at java.lang.Thread.run(Thread.java:748)
```

This is the code for reference:
```python
xgb_estimator = XGBoostSageMakerEstimator(
    trainingInstanceType="ml.m4.xlarge",
    trainingInstanceCount=1,
    endpointInstanceType="ml.m4.xlarge",
    endpointInitialInstanceCount=1,
    trainingProjectedColumns = ["features","label"],
    sagemakerRole=IAMRole(iam_role))

xgb_estimator.setNumRound(2)
xgb_model = xgb_estimator.fit(algoInput)
```

**Comment by andremoeller** [comment]
Hi @mostafa-time ,

Yeah, it seems like we aren't handling this case correctly. We'll work on this and post an update. Thanks!

**Comment by mostafa-time** [comment]
Hi @andremoeller!

Do you guys have ETA for fixing this bug? We are very interested to use SageMaker but this bug is currently on the way.

**Comment by andremoeller** [comment]
Hey @mostafa-time ,

We're currently working on this and expect to have a PR within the next week.

As an interim measure, a couple things I'd suggest are to select only the "features" and "label" columns as you had done originally (using the `Estimator` directly), or, if you'd prefer to use `Pipeline`s, to create a custom `Transformer` that drops the other columns in its `transform()`, and put that `Transformer` immediately before the `XGBoostSageMakerEstimator`.

Thank you for your patience and your interest in SageMaker, and sorry for the inconvenience!

**Comment by yangaws** [comment]
Hi @mostafa-time 

Thanks for using sagemaker!

I am working on a fix of this issue. I have already done code change and waiting for integ tests. Will reply to this issue after I create a PR.

Thanks for patience and sorry for the inconvenience.

**Comment by mostafa-time** [comment]
Thanks @andremoeller, we have a functioning system in production (with MLeap), we just wanted to get it working with SageMaker, and thanks @yangaws !

**Comment by yangaws** [comment]
Tracked in PR https://github.com/aws/sagemaker-spark/pull/18

**Comment by yangaws** [comment]
Hi @mostafa-time ,

Thanks for the patience. The code change passes all tests and is merged to master and you can specify trainingProjectedColumns = ["label","features"] now after building sagemaker from source. 

If you have any questions, feel free to reopen this issue.

**Comment by mostafa-time** [comment]
Hi @yangaws,

I quickly run the same code and I got the same previous error, however I did not build sagemaker from the source. I assumed it will have the latest version when I spin up a new notebook instance. Is that right?

**Comment by yangaws** [comment]
Hi @mostafa-time ,

To fix this bug in a new notebook, besides code change in this repo, we also need to go through several release processes. So currently to assume the code change, you can only build it from source. Sorry for the inconvenience. I will get back to this issue after all release process finished.

I suggest to test locally first. Could you try clone the codes from master, build sagemaker_pyspark from source using "python setup.py install" and write same tests in a python file by using sagemaker_pyspark. 

BTW, I read your original code and have one doubt. From spark source code, https://github.com/apache/spark/blob/master/mllib/src/main/scala/org/apache/spark/ml/source/libsvm/LibSVMRelation.scala#L79
I think ["features", "label"] doesn't satisfy libsvm schema. You probably need to pass trainingProjectedColumns = ["label","features"]

**Comment by yangaws** [comment]
Hi @mostafa-time ,

Is your issue fixed? We released a lot things after our last communication. I tried things in my notebook and did not see the problem again.

**Comment by mostafa-time** [comment]
Hi @yangaws ,

Have not tried it recently. I'll try it out again and let you know when I get time.

Thanks for following up.

**Comment by KobaKhit** [comment]
FYI, I tried using the `trainingProjectedColumns` and it is important that the label column name is first, ex. g. `trainingProjectedColumns = ['label_col','feature_col']`. Otherwise, it will throw an illegal schema exception.
