### ISSUE TITLE
XGBoostSageMakerEstimator.fit() isn't using the configured IAM sagemakerRole

### ISSUE THREAD

**Issue by sawyercade** [aws/sagemaker-spark#27]
I have an IAM role with AmazonSageMakerFullAccess policy, and am setting that as my role on both `spark.conf` and on the `XGBoostSageMakerEstimator.sagemakerRole`:

```
#Train a SageMaker XGBoost estimator
from pyspark import SparkContext, SparkConf
from sagemaker_pyspark import IAMRole, classpath_jars
from sagemaker_pyspark.algorithms import XGBoostSageMakerEstimator

spark.conf.set("spark.driver.extraClassPath", ":".join(classpath_jars()))

spark.conf.set("com.amazonaws.services.sagemaker.sparksdk.sagemakerrole", "arn:aws:iam::316286097077:role/service-role/AmazonSageMaker-ExecutionRole-20180301T115701")

iam_role = "arn:aws:iam::316286097077:role/service-role/AmazonSageMaker-ExecutionRole-20180301T115701"

xg_estimator = XGBoostSageMakerEstimator(trainingInstanceType="m1.m4.xlarge",
                                         trainingInstanceCount=1,
                                        endpointInstanceType="ml.m4.xlarge",
                                        endpointInitialInstanceCount=1,
                                        sagemakerRole=IAMRole(iam_role))

xg_estimator.setObjective("binary:logistic")
xg_estimator.setNumRound(50)
```

`print(xg_estimator.sagemakerRole)` returns the expected SageMaker ExecutionRole.

However, when I run `xg_estimator.fit(train)`, I get the following error, indicating that the IAM role being used to execute the createTrainingJob request is the default role on my EMR cluster, not the role I configured above on the estimator.

```An error occurred while calling o877.fit.
: java.lang.RuntimeException: Training job couldn't be completed.
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.runTrainingJob(SageMakerEstimator.scala:407)
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.fit(SageMakerEstimator.scala:311)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.amazonaws.services.sagemaker.model.AmazonSageMakerException: User: arn:aws:sts::316286097077:assumed-role/EMR_EC2_DefaultRole/i-0c8b1b2ec4af67039 is not authorized to perform: sagemaker:CreateTrainingJob on resource: arn:aws:sagemaker:us-west-2:316286097077:training-job/trainingjob-7c2da2b9771a-2018-03-02t23-02-25-437 (Service: AmazonSageMaker; Status Code: 400; Error Code: AccessDeniedException; Request ID: b33ff678-33d8-45a7-beaa-146e4adff3de)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1639)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1304)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1056)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:743)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:717)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.amazonaws.services.sagemaker.AmazonSageMakerClient.doInvoke(AmazonSageMakerClient.java:1832)
	at com.amazonaws.services.sagemaker.AmazonSageMakerClient.invoke(AmazonSageMakerClient.java:1808)
	at com.amazonaws.services.sagemaker.AmazonSageMakerClient.executeCreateTrainingJob(AmazonSageMakerClient.java:641)
	at com.amazonaws.services.sagemaker.AmazonSageMakerClient.createTrainingJob(AmazonSageMakerClient.java:617)
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.runTrainingJob(SageMakerEstimator.scala:408)
	... 12 more```

**Comment by nadiaya** [comment]
Are you running it through SageMaker Notebook using Sparkmagic kernel?
Or on EMR cluster itself?

**Comment by yangaws** [comment]
Hi @sawyercade 

I run your scripts with my execution role on my notebook with python3_conda kernel. Training and inference are both good. I have not seen the bug you posted.

Could you provide more details about this? Are you running this on sagemaker notebook? What kernel? Or you run it somewhere else?

Thanks

**Comment by haowang-ms89** [comment]
@yangaws @nadiaya 
Hi,
I have the same issue (the IAM role reported in the exception is not the role I set in the XGBoostSageMakerEstimator initializer). The environment is EMR 5.13.0+Zeppline 0.7.3+Spark 2.3.0, instead of SageMaker Notebook.

**Comment by andremoeller** [comment]
Hi @haowang-ms89 ,

Looking into this some more: the actual issue is probably that the role being used by the cluster doesn't have permission to make calls to SageMaker. The EMR default role only has policy AmazonElasticMapReduceRole, but it needs to be able to make CreateTrainingJob calls, CreateModel, etc.

You can get all the necessary permissions (and more) by attaching the AmazonSageMakerFullAccess policy to the IAM role you're using in your cluster.

**Comment by haowang-ms89** [comment]
Hi @andremoeller 
I attached the AmazonSageMakerFullAccess policy to the EMR cluster IAM role, but still got the same unauthorized error message. I am also wondering when using EMR like this, will the IAM role setting in the initializer take effect?

**Comment by andremoeller** [comment]
Hi @haowang-ms89 

Yeah, my mistake -- I think you actually need to attach AmazonSageMakerFullAccess to EMR_EC2_DefaultRole, if that's what you're using.

**Comment by haowang-ms89** [comment]
@andremoeller 
In fact, I attach the AmazonSageMakerFullAccess to both EMR_EC2_DefaultRole and EMR_DefaultRole, does not work :(

**Comment by haowang-ms89** [comment]
@andremoeller 
Hi Andre, I tried again this morning and it worked... don't really know why. Now the model is trained, but I got some format error like before when I call transform(). I will ask in that thread. Thanks for your time!

**Comment by alexkayal** [comment]
Not sure if this helps but you may have to create a role from scratch that has full policies allowing full access to sagemaker and emr/ec2. You need to also add both sagemaker and ec2 to the trust relationships of that role.

Thing is, if you dont create a new role, as in if you attach policies to an existing role, you won't have an instance profile, which will be a blocking issue at some point.
