### ISSUE TITLE
Failing to read data from s3 to a spark dataframe due to failing to read the config file

### ISSUE THREAD

**Issue by phesami** [aws/sagemaker-spark#61]
### System Information
- **Spark or PySpark**: pyspark
- **SDK Version**: NA
- **Spark Version**: v2.3.1
- **Algorithm (e.g. KMeans)**: NA

### Describe the problem
I'm trying to read a csv file on an s3 bucket (for which the sagemaker notebook has full access to) into a spark dataframe however I am hitting the following issue where `sagemaker-spark_2.11-spark_2.2.0-1.1.1.jar` can't be found.

### Minimal repo / logs
`Py4JJavaError: An error occurred while calling o388.csv.
: java.util.ServiceConfigurationError: org.apache.spark.sql.sources.DataSourceRegister: Error reading configuration file
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.parse(ServiceLoader.java:309)
	at java.util.ServiceLoader.access$200(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.hasNextService(ServiceLoader.java:357)
	at java.util.ServiceLoader$LazyIterator.hasNext(ServiceLoader.java:393)
	at java.util.ServiceLoader$1.hasNext(ServiceLoader.java:474)
	at scala.collection.convert.Wrappers$JIteratorWrapper.hasNext(Wrappers.scala:42)
	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:247)
	at scala.collection.TraversableLike$class.filter(TraversableLike.scala:259)
	at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:614)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:190)
	at org.apache.spark.sql.DataFrameReader.csv(DataFrameReader.scala:596)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker_pyspark/jars/sagemaker-spark_2.11-spark_2.2.0-1.1.1.jar (No such file or directory)
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:219)
	at java.util.zip.ZipFile.<init>(ZipFile.java:149)
	at java.util.jar.JarFile.<init>(JarFile.java:166)
	at java.util.jar.JarFile.<init>(JarFile.java:103)
	at sun.net.www.protocol.jar.URLJarFile.<init>(URLJarFile.java:93)
	at sun.net.www.protocol.jar.URLJarFile.getJarFile(URLJarFile.java:69)
	at sun.net.www.protocol.jar.JarFileFactory.get(JarFileFactory.java:84)
	at sun.net.www.protocol.jar.JarURLConnection.connect(JarURLConnection.java:122)
	at sun.net.www.protocol.jar.JarURLConnection.getInputStream(JarURLConnection.java:150)
	at java.net.URL.openStream(URL.java:1045)
	at java.util.ServiceLoader.parse(ServiceLoader.java:304)
	... 26 more
`

- **Exact command to reproduce**:
bucket = "mybucket"
prefix = "folder/myfile.csv"
df = spark.read.csv("s3://{}/{}/".format(bucket,prefix))

update:
I only see this issue with conda_python3! it works fine in conda_python2.

**Comment by yangaws** [comment]
Hi @phesami,

Could you check if the jar is actually there? You could do the following:

1, Check the path in the error message: /home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker_pyspark/jars
Does this path have the jar reported missing?

2, In notebook do:

import sagemaker_pyspark
jars = sagemaker_pyspark.classpath_jars()
print(jars)

Does the list printed contain the jar reported missing?

And when did you create this notebook instance? If that's long time ago, could you try starting a new one and run things again?

Thanks

**Comment by phesami** [comment]
Hi @yangaws 
1. No the missing file doesn't exist. I only see `sagemaker-spark_2.11-spark_2.2.0-1.1.3.jar` instead of `sagemaker-spark_2.11-spark_2.2.0-1.1.1.jar`.
2. Same thing! I only see  `sagemaker-spark_2.11-spark_2.2.0-1.1.3.jar`

**Comment by yangaws** [comment]
Hi @phesami ,

Did you try creating a new notebook instance and retrying the codes you have?

And also, could you do same thing for python 2 kernel to see if the the jar file is 1.1.1 or 1.1.3 using same method?

1, Check /home/ec2-user/anaconda3/envs/python2/lib/python2.7/site-packages/sagemaker_pyspark/jars

2, Or in notebook with python2 kernel, do 

import sagemaker_pyspark
jars = sagemaker_pyspark.classpath_jars()
print(jars)

**Comment by phesami** [comment]
@yangaws I had created my notebook 4 days ago but I tried to recreate a new one and now I don't see the issue anymore! Thanks for the help!

**Comment by yangaws** [comment]
@phesami  
Cool. Glad it works!

**Comment by srilalithaveerubhotla** [comment]
hello i am getting the same error  with json file can you tell me the shortest way to load in pysaprk

**Comment by bharath02** [comment]
data=spark.read.csv("s3a://file_path ") getting py4jjavaerror
py4JJavaError: An error occurred while calling o88.csv. : java.lang.NoClassDefFoundError: org/jets3t/service/S3ServiceException
