### ISSUE TITLE
Getting error: failed for reason: 'InternalServerError: We encountered an internal error. Please try again

### ISSUE THREAD

**Issue by nirmaljuthani** [aws/sagemaker-spark#76]
Please fill out the form below.

### System Information
- **Spark or PySpark**:
PySpark
- **SDK Version**:
- **Spark Version**:
v2.2.1
- **Algorithm (e.g. KMeans)**:
pyspark_mnist_pca_mllib_kmeans

### Describe the problem
Describe the problem or feature request clearly here.

While running the example sageMaker notebook, pyspark_mnist_pca_mllib_kmeans I get the following error during the model.fit step.
### Minimal repo / logs

---------------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
<ipython-input-5-6093e9ad22ee> in <module>()
      1 # Train
----> 2 pipelineModelSparkSM = pipelineSparkSM.fit(trainingData)

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyspark/ml/base.py in fit(self, dataset, params)
     62                 return self.copy(params)._fit(dataset)
     63             else:
---> 64                 return self._fit(dataset)
     65         else:
     66             raise ValueError("Params must be either a param map or a list/tuple of param maps, "

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyspark/ml/pipeline.py in _fit(self, dataset)
    106                     dataset = stage.transform(dataset)
    107                 else:  # must be an Estimator
--> 108                     model = stage.fit(dataset)
    109                     transformers.append(model)
    110                     if i < indexOfLastEstimator:

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker_pyspark/SageMakerEstimator.py in fit(self, dataset)
    255         """
    256         self._transfer_params_to_java()
--> 257         return self._call_java("fit", dataset)
    258 
    259     def copy(self, extra):

~/anaconda3/envs/python3/lib/python3.6/site-packages/sagemaker_pyspark/wrapper.py in _call_java(self, name, *args)
     76             java_args.append(self._py2j(arg))
     77 
---> 78         java_value = super(SageMakerJavaWrapper, self)._call_java(name, *java_args)
     79         return SageMakerJavaWrapper._from_java(java_value)
     80 

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyspark/ml/wrapper.py in _call_java(self, name, *args)
     49         sc = SparkContext._active_spark_context
     50         java_args = [_py2java(sc, arg) for arg in args]
---> 51         return _java2py(sc, m(*java_args))
     52 
     53     @staticmethod

~/anaconda3/envs/python3/lib/python3.6/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1131         answer = self.gateway_client.send_command(command)
   1132         return_value = get_return_value(
-> 1133             answer, self.gateway_client, self.target_id, self.name)
   1134 
   1135         for temp_arg in temp_args:

~/anaconda3/envs/python3/lib/python3.6/site-packages/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

~/anaconda3/envs/python3/lib/python3.6/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    317                 raise Py4JJavaError(
    318                     "An error occurred while calling {0}{1}{2}.\n".
--> 319                     format(target_id, ".", name), value)
    320             else:
    321                 raise Py4JError(

Py4JJavaError: An error occurred while calling o64.fit.
: java.lang.RuntimeException: Training job couldn't be completed.
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.runTrainingJob(SageMakerEstimator.scala:410)
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.fit(SageMakerEstimator.scala:314)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:280)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Training job 'sparksm-2-trainingJob-966313780fde-2018-12-19T19-30-02-992' failed for reason: 'InternalServerError: We encountered an internal error. Please try again.'
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.awaitTrainingCompletion(SageMakerEstimator.scala:438)
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator.runTrainingJob(SageMakerEstimator.scala:412)
	... 12 more
- **Exact command to reproduce**:
Running this example notebook given in the following link:
[jupyter notebook](https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-spark/pyspark_mnist/pyspark_mnist_pca_mllib_kmeans.ipynb
)
on a jupyter notebook instance type ml.t2.medium in aws sageMaker.

**Comment by nirmaljuthani** [comment]
ok, I realized this error is coming due to notebook instance type ml.t2.medium. The given example runs in ml.m4.xlarge and since my instance was not having sufficient resources it gave that internal error. I guess it would help, if instead of internal error, some other error which specifies the reason for failure was shown.
