### ISSUE TITLE
hadoop-aws dependency issue

### ISSUE THREAD

**Issue by oatmealraisin** [aws/sagemaker-spark#87]
Hey all, sorry if this has been brought up before, I'm just having an issue with managing a few of the AWS related libraries for Spark.

### System Information
- **Spark**:
- **aws-java-sdk-1.11.238,sagemaker-spark_2.11:spark_2.2.0-1.0**:
- **2.2.0**:
- **XGBoost**:

### Describe the problem

Issue resolving dependency for Hadoop-AWS, which depends on aws-java-sdk-1.10.6

```
Java 1.8
Hadoop 2.8.1
Spark 2.2.0
```

I'm not sure how I should resolve hadoop-aws wanting aws-sdk ~ 1.7.4, with the sagemaker-spark dependency wanting ~ 1.11.238.

### Minimal repo / logs

Using above versions, run spark-submit, providing SageMaker-Spark recommended flags, and the main class of the application..

```
./bin/spark-submit --deploy-mode=client \
            --master 'spark://127.0.0.1:7077' \
            --conf 'spark.driver.userClassPathFirst=true' \
            --conf 'spark.executor.userClassPathFirst=true' \
            --conf 'spark.driver.extraClassPath=:/usr/local/hadoop/share/hadoop/tools/lib/*' \
            --conf 'spark.executor.extraClassPath=:/usr/local/hadoop/share/hadoop/tools/lib/*' \
            --packages 'com.amazonaws:aws-java-sdk:1.11.238,com.amazonaws:sagemaker-spark_2.11:spark_2.2.0-1.0' \
            --class 'com.main.scala.MyClass'
```

The error should come quickly,

```
19/07/30 03:47:31 WARN streaming.FileStreamSink: Error while looking for metadata directory.
Exception in thread "main" java.lang.ClassCastException: org.apache.hadoop.fs.s3a.S3AFileSystem cannot be cast to org.apache.hadoop.fs.FileSystem
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2810)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:100)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2848)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2830)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:389)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:356)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:350)
        at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:348)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
        at scala.collection.immutable.List.foreach(List.scala:381)
        at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
        at scala.collection.immutable.List.flatMap(List.scala:344)
        at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:348)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:156)
        at com.bacrey.applications.BacreyPreprocess$.main(BacreyPreprocess.scala:194)
        at com.bacrey.applications.BacreyPreprocess.main(BacreyPreprocess.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:755)
        at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)
        at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

- **Exact command to reproduce**:

```
./bin/spark-submit --deploy-mode=client \
            --master 'spark://127.0.0.1:7077' \
            --conf 'spark.driver.userClassPathFirst=true' \
            --conf 'spark.executor.userClassPathFirst=true' \
            --conf 'spark.driver.extraClassPath=:/usr/local/hadoop/share/hadoop/tools/lib/*' \
            --conf 'spark.executor.extraClassPath=:/usr/local/hadoop/share/hadoop/tools/lib/*' \
            --packages 'com.amazonaws:aws-java-sdk:1.11.238,com.amazonaws:sagemaker-spark_2.11:spark_2.2.0-1.0' \
            --class 'com.main.scala.MyClass'
```

Additionally, if the 'userClassPathFirst' flags are toggled, this output is produced when trying to create a client:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.SDKGlobalConfiguration.isInRegionOptimizedModeEnabled()
```

**Comment by icywang86rui** [comment]
@oatmealraisin  
Could you please attach the entire output of your spark-submit command?

**Comment by laurenyu** [comment]
closing due to inactivity. feel free to reopen if necessary.
