### ISSUE TITLE
Issue while getting SAGEMAKER IMAGE.

### ISSUE THREAD

**Issue by TridevNS** [aws/sagemaker-spark#88]
Hi Team, 
We are facing an issue with a spark-sagemaker.

Example KMeans:
```
          val estimator = new KMeansSageMakerEstimator(
                         sagemakerRole = IAMRole(roleArn),
                         trainingInstanceType = trainingInstanceType,
                         trainingInstanceCount = trainingInstanceCount,
                         endpointInstanceType = endpointInstanceType,
                         endpointInitialInstanceCount = endpointInitialInstanceCount)
                       .setK(k).setFeatureDim(featureDim)

          val kmodel = estimator.fit(dataFrame)
```

Also tried by passing the Region parameter.

And it used to work good, from last 4 weeks we are getting below exception.

### Logs
```
Exception in thread "main" java.lang.NoSuchFieldError: US_EAST_2
at com.amazonaws.services.sagemaker.sparksdk.algorithms.SagerMakerRegionAccountMaps$.(ImageURIProvider.scala:38)
at com.amazonaws.services.sagemaker.sparksdk.algorithms.SagerMakerRegionAccountMaps$.(ImageURIProvider.scala)
at com.amazonaws.services.sagemaker.sparksdk.algorithms.KMeansSageMakerEstimator$.(KMeansSageMakerEstimator.scala:145)
at com.amazonaws.services.sagemaker.sparksdk.algorithms.KMeansSageMakerEstimator$.(KMeansSageMakerEstimator.scala)
at com.spark.KMeansSageMaker$.main(KMeansSageMaker.scala:27)
at com.spark.KMeansSageMaker.main(KMeansSageMaker.scala)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/07/20 16:28:19 INFO SparkContext: Invoking stop() from shutdown hook
19/07/20 16:28:19 INFO SparkUI: Stopped Spark web UI at http://172.31.50.74:4040
```

### System Information
- **Spark or PySpark**: Spark
- **SDK Version**:  spark_2.1.1-1.0
- **Spark Version**:  2.1.0
- **Algorithm (e.g. KMeans)**: All

Also tried by upgrading the SDK version to spark_2.2.0-1.0 and spark to 2.2.0.

Thanks,
Tridev

**Comment by icywang86rui** [comment]
@TridevNS 
Could you show me the how did you pass the region into the estimator? Is this stack trace from the code with the region passed in? What is the error/stack trace without the region?

**Comment by TridevNS** [comment]
> @TridevNS
> Could you show me the how did you pass the region into the estimator? Is this stack trace from the code with the region passed in? What is the error/stack trace without the region?

Below is code with region:

```    val estimator = new KMeansSageMakerEstimator(
      sagemakerRole = IAMRole(roleArn),
      trainingInstanceType = "ml.p2.xlarge",
      trainingInstanceCount = 1,
      endpointInstanceType = "ml.c4.xlarge",
      endpointInitialInstanceCount = 1, region = Some(Regions.US_EAST_1.getName))
      .setK(10).setFeatureDim(784)

    // train
    val model = estimator.fit(trainingData)```

Above error/stack is without region. But with the region also it looks the same.

Below is with the region:
```
Exception in thread "main" java.lang.NoSuchFieldError: US_EAST_2
	at com.amazonaws.services.sagemaker.sparksdk.algorithms.SagerMakerRegionAccountMaps$.<init>(ImageURIProvider.scala:38)
	at com.amazonaws.services.sagemaker.sparksdk.algorithms.SagerMakerRegionAccountMaps$.<clinit>(ImageURIProvider.scala)
	at com.amazonaws.services.sagemaker.sparksdk.algorithms.KMeansSageMakerEstimator$.<init>(KMeansSageMakerEstimator.scala:145)
	at com.amazonaws.services.sagemaker.sparksdk.algorithms.KMeansSageMakerEstimator$.<clinit>(KMeansSageMakerEstimator.scala)
	at com.spark.KMeansSageMaker$.main(KMeansSageMaker.scala:28)
	at com.spark.KMeansSageMaker.main(KMeansSageMaker.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/08/02 13:52:06 INFO SparkContext: Invoking stop() from shutdown hook
19/08/02 13:52:06 INFO SparkUI: Stopped Spark web UI at http://172.31.33.238:4040
19/08/02 13:52:06 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/08/02 13:52:06 INFO MemoryStore: MemoryStore cleared
19/08/02 13:52:06 INFO BlockManager: BlockManager stopped
19/08/02 13:52:06 INFO BlockManagerMaster: BlockManagerMaster stopped
19/08/02 13:52:06 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/08/02 13:52:06 INFO SparkContext: Successfully stopped SparkContext
19/08/02 13:52:06 INFO ShutdownHookManager: Shutdown hook called
19/08/02 13:52:06 INFO ShutdownHookManager: Deleting directory /mnt/tmp/spark-518caa68-d669-4474-82ce-fed71090e7df ```

**Comment by icywang86rui** [comment]
Does the stack trace also say 
``Exception in thread "main" java.lang.NoSuchFieldError: US_EAST_2``
Even if you put this in the estimator constructor ``region = Some(Regions.US_EAST_1.getName))``.

I think there might be something wrong with the aws java sdk you are using since the key ``US_EAST_2`` is from the java sdk code. Couple things you can try here:

* bypass the image uri building by adding this in the estimator constructor:
```
trainingImage="382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1"
```
* upgrading sagemaker-pyspark version

**Comment by TridevNS** [comment]
> Does the stack trace also say
> `Exception in thread "main" java.lang.NoSuchFieldError: US_EAST_2`
> Even if you put this in the estimator constructor `region = Some(Regions.US_EAST_1.getName))`.

We faced the issue after passing the region.

Thanks, I will test with your suggestions and let you know.

**Comment by TridevNS** [comment]
> I think there might be something wrong with the aws java sdk you are using since the key `US_EAST_2` is from the java sdk code. Couple things you can try here:

We don't have aws java SDK in our dependencies and below are the dependencies we have.  

``` <properties>
        <java.version>1.8</java.version>
        <spark.version>2.1.0</spark.version>
        <hadoop.version>2.6.0</hadoop.version>
        <scala.version>2.11.8</scala.version>
        <scala.binary.version>2.11</scala.binary.version>
        <sagemaker-spark.version>spark_2.1.1-1.0</sagemaker-spark.version>
    </properties>```

**Comment by TridevNS** [comment]
> * bypass the image uri building by adding this in the estimator constructor:
> 
> ```
> trainingImage="382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1"
> ```

Tried the above suggestion.

```    val estimator = new SageMakerEstimator(
      trainingImage =
        "382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1",
      modelImage =
        "382416733822.dkr.ecr.us-east-1.amazonaws.com/kmeans:1",
      requestRowSerializer = new ProtobufRequestRowSerializer(),
      responseRowDeserializer = new KMeansProtobufResponseRowDeserializer(),
      hyperParameters = Map("k" -> "10", "feature_dim" -> "784"),
      sagemakerRole = IAMRole(roleArn),
      trainingInstanceType = "ml.p2.xlarge",
      trainingInstanceCount = 1,
      endpointInstanceType = "ml.c4.xlarge",
      endpointInitialInstanceCount = 1)

    // train
    val model = estimator.fit(trainingData)```

And now we are facing below issue:

```Exception in thread "main" java.lang.NoSuchMethodError: com.amazonaws.auth.DefaultAWSCredentialsProviderChain.getInstance()Lcom/amazonaws/auth/DefaultAWSCredentialsProviderChain;
	at com.amazonaws.client.builder.AwsClientBuilder.resolveCredentials(AwsClientBuilder.java:125)
	at com.amazonaws.client.builder.AwsClientBuilder.access$100(AwsClientBuilder.java:52)
	at com.amazonaws.client.builder.AwsClientBuilder$SyncBuilderParams.<init>(AwsClientBuilder.java:412)
	at com.amazonaws.client.builder.AwsClientBuilder.getSyncClientParams(AwsClientBuilder.java:354)
	at com.amazonaws.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
	at com.amazonaws.services.sagemaker.AmazonSageMakerClientBuilder.defaultClient(AmazonSageMakerClientBuilder.java:44)
	at com.amazonaws.services.sagemaker.sparksdk.SageMakerEstimator$.$lessinit$greater$default$25(SageMakerEstimator.scala:202)
	at com.spark.KMeansSageMaker$.main(KMeansSageMaker.scala:39)
	at com.spark.KMeansSageMaker.main(KMeansSageMaker.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:738)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
19/08/12 11:08:42 INFO SparkContext: Invoking stop() from shutdown hook
19/08/12 11:08:42 INFO SparkUI: Stopped Spark web UI at http://172.31.43.5:4040
19/08/12 11:08:42 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/08/12 11:08:42 INFO MemoryStore: MemoryStore cleared
19/08/12 11:08:42 INFO BlockManager: BlockManager stopped
```

**Comment by ChoiByungWook** [comment]
Apologies to throw you in a loop.

Can you try updating your sagemaker-spark version to the latest?

https://mvnrepository.com/artifact/com.amazonaws/sagemaker-spark_2.11/spark_2.2.0-1.2.5

I'm really curious as to why this older version of sagemaker-spark is all of a sudden failing, when it seems like not much has changed.

Just wondering, do you have a separate version of the AWS SDK installed? I'm wondering if they made a breaking change and moved the region field elsewhere.

Thanks!

**Comment by TridevNS** [comment]
> Apologies for the late response and to throw you in a loop.
> 
> Can you try updating your sagemaker-spark version to the latest?
> 
> https://mvnrepository.com/artifact/com.amazonaws/sagemaker-spark_2.11/spark_2.2.0-1.2.5
> 
> I'm really curious as to why this older version of sagemaker-spark is all of a sudden failing, when it seems like not much has changed.
> 
> Just wondering, do you have a separate version of the AWS SDK installed? I'm wondering if they made a breaking change and moved the region field elsewhere.
> 
> Thanks!
> 
> Reference:
> 
> [aws/aws-sdk-java#1611](https://github.com/aws/aws-sdk-java/issues/1611)
> https://stackoverflow.com/questions/49330745/error-with-aws-emr-client-java-lang-nosuchfielderror-signing-region

Thanks. After changing the version it worked.

I will close the ticket.
