### ISSUE TITLE
ValueError: Param Param(parent=u'Identifiable_6ae526df2299', name='lambda', doc='L2 regularization term on weights, increase this value will make model more conservative.') does not belong to Identifiable_6ae526df2299.

### ISSUE THREAD

**Issue by SarathNair28** [aws/sagemaker-spark#93]
Please fill out the form below.

### System Information
- **Spark or PySpark**: PySpark
- **SDK Version**: 
- **Spark Version**: Spark 2.4.3
- **Algorithm (e.g. KMeans)**: XG Boost

### Describe the problem
I am getting the following error while trying to train a model using XgBoost on pyspark notebook instance running on an EMR Spark.
--------------------------------------------------------------------------------------------
```
Param Param(parent=u'Identifiable_6ae526df2299', name='lambda', doc='L2 regularization term on weights, increase this value will make model more conservative.') does not belong to Identifiable_6ae526df2299.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sagemaker_pyspark/SageMakerEstimator.py", line 256, in fit
    self._transfer_params_to_java()
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/wrapper.py", line 123, in _transfer_params_to_java
    if self.isSet(param):
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 311, in isSet
    param = self._resolveParam(param)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 414, in _resolveParam
    self._shouldOwn(param)
  File "/usr/lib/spark/python/lib/pyspark.zip/pyspark/ml/param/__init__.py", line 403, in _shouldOwn
    raise ValueError("Param %r does not belong to %r." % (param, self))
ValueError: Param Param(parent=u'Identifiable_6ae526df2299', name='lambda', doc='L2 regularization term on weights, increase this value will make model more conservative.') does not belong to Identifiable_6ae526df2299.
```
--------------------------------------------------------------------------------------------

### Minimal repo / logs
Please provide any logs and a bare minimum reproducible test case, as this will be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

- **Exact command to reproduce**:
I had been trying to run the below code:
```
xgboost_estimator = XGBoostSageMakerEstimator(
    trainingInstanceType="ml.m4.xlarge",
    trainingInstanceCount=1,
    endpointInstanceType="ml.m4.xlarge",
    endpointInitialInstanceCount=1,
    sagemakerRole=IAMRole(role))

xgboost_estimator.setObjective('multi:softmax')
xgboost_estimator.setNumRound(25)
xgboost_estimator.setNumClasses(10)

xgboost_model = xgboost_estimator.fit(training_data)

transformed_data = xgboost_model.transform(test_data)
transformed_data.show()
```

**Comment by ChoiByungWook** [comment]
Hello @SarathNair28,

Thanks for bringing this to our attention and apologies for the late response.

For clarification, when exactly does this error occur? Is it during the `fit` or `transform` call?

Reference:
* https://github.com/aws/sagemaker-spark/blob/master/sagemaker-pyspark-sdk/src/sagemaker_pyspark/algorithms/XGBoostSageMakerEstimator.py#L178
* https://spark.apache.org/docs/2.2.0/api/python/_modules/pyspark/ml/param.html

I am a little bit confused as to what caused this error, as the corresponding param in the Spark SDK exists: https://github.com/aws/sagemaker-spark/blob/master/sagemaker-spark-sdk/src/main/scala/com/amazonaws/services/sagemaker/sparksdk/algorithms/XGBoostSageMakerEstimator.scala#L161

**Comment by laurenyu** [comment]
closing due to inactivity. feel free to reopen if necessary.

**Comment by michaelhsieh42** [comment]
Having the same issue here. It is happening at .fit call. Notebook used: https://github.com/awslabs/amazon-sagemaker-examples/blob/master/sagemaker-spark/pyspark_mnist/pyspark_mnist_xgboost.ipynb on an EMR cluster emr-5.28.0, spark 2.4.4.

**Comment by Karrthik-Arya** [comment]
I am also facing the same issue while running a .fit call with an XGBoost estimator
